/**
 * Child session and worktree identity generation (issue #17 §7.4).
 *
 * All identifiers are host-generated, conductor-owned, and uniquely
 * namespaced. The cleanup path verifies that worktree paths are beneath
 * `stateDir` and branch names carry the `conductor/` prefix — this
 * generation path is the single source of truth for those invariants.
 *
 * All three functions are pure: no I/O, no SDK imports, no time-based
 * randomness. Tests inject a deterministic `randomBytes` via the
 * `withRandomBytes` override pattern.
 */

// ─── Child ID ───────────────────────────────────────────────────────

/**
 * Generate a unique child identifier.
 * Uses `node:crypto.randomBytes` for sufficient uniqueness without
 * cryptographic requirements. The format is `child-<hex16>` where the
 * hex portion is 16 lowercase hex digits (8 random bytes).
 *
 * Not cryptographically random — use for session keys only, not auth.
 */
export function generateChildId(randomBytes: (n: number) => Buffer = defaultRandomBytes): string {
  const bytes = randomBytes(8);
  return `child-${bytes.toString("hex")}`;
}

/** Default `randomBytes` backed by `node:crypto.randomBytes`. */
function defaultRandomBytes(n: number): Buffer {
  // `node:crypto` is always available; lazy-import only for the
  // non-test path to keep the module side-effect-free in Node.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { randomBytes } = require("node:crypto") as { randomBytes: (n: number) => Buffer };
  return randomBytes(n);
}

// ─── Worktree path ──────────────────────────────────────────────────

/**
 * Generate the worktree directory path for a child.
 * Always beneath `<stateDir>/worktrees/<childId>`.
 *
 * The cleanup path (Phase 3, spec §11) verifies this prefix so the
 * primary checkout is never accidentally removed.
 */
export function generateWorktreePath(stateDir: string, childId: string): string {
  return `${stateDir}/worktrees/${childId}`;
}

// ─── Branch name ───────────────────────────────────────────────────

/**
 * Generate the Git branch name for a child worktree.
 * Always carries the `conductor/` prefix so the cleanup path can
 * identify conductor-owned branches and avoid touching user branches.
 *
 * Format: `conductor/<childId>`
 */
export function generateBranchName(childId: string): string {
  return `conductor/${childId}`;
}

// ─── Validation helpers (used by worktree.ts for defensive input checks) ─

/**
 * Validate that a childId matches the format generated by `generateChildId`.
 * Used by the worktree manager to sanitize inputs before constructing git
 * commands (defense-in-depth; the manager only operates on host-generated IDs).
 *
 * Pattern: `child-[0-9a-f]{16}`
 */
const CHILD_ID_PATTERN = /^child-[0-9a-f]{16}$/;

export function isValidChildId(childId: string): boolean {
  return CHILD_ID_PATTERN.test(childId);
}

// ─── Role type re-export for consumers ─────────────────────────────

/** Re-export the Role type so delegation consumers don't need the full index. */
export type { Role } from "../../index.js";
